# Generated by Django 4.1.3 on 2023-04-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lemon", "0002_note_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
