# Generated by Django 4.1.3 on 2023-07-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lemon", "0005_person_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
